### ISSUE TITLE
点击borrow，在没有存款的情况下 应显示 0

### ISSUE THREAD

**Issue by sunjeon** [sunjeon/MyMuffin#3]
此处展示为NaN，只有这一个token是这样。
![截屏2022-03-15 17 44 47](https://user-images.githubusercontent.com/39148294/158350740-30efc519-7f1a-46f8-aa72-09c34b052ab9.png)

**Comment by evan0412** [comment]
fixed

**Comment by sunjeon** [comment]
fixed
