### ISSUE TITLE
可借款最大值调整

### ISSUE THREAD

**Issue by cloud8little** [sunjeon/MyMuffin#5]
![df19411e64c36b2833ed63092b253b5](https://user-images.githubusercontent.com/34291844/158357337-f428eaf3-d7ef-4f97-8aa0-e3f3feded2c8.png)

取min(用户可以借的最大值, 该币种可供借出的值)

**Comment by evan0412** [comment]
fixed

**Comment by cloud8little** [comment]
已验证
